default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: gtd_development

test:
  <<: *default
  database: gtd_test

production:
  adapter: postgresql
  encoding: utf8
  database: gtd-bot
  username: lunar
  password: "<%= ENV.fetch('GTD_BOT_DATABASE_PASSWORD') %>"
  pool: 25
  min_messages: WARNING
