# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 308e1635e836659e8995f57d5a377351cc77121edad164d42fe99d0b6e83db8f60b507f188dce3f7a37fd8e9f60d985c486e39d941719bac754e7bb93c69192e

test:
  secret_key_base: 44f99bd0c49dced3a97e5e9ad2bbcf3481235b265e4a7dd35abf1d28060653e79c724fbc506dd69f07154684a053461852799ff622e20ee2ea11f620eb3fd282

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
